version: '3.0'

# x-base: &base
#   networks: 
#     - microfrontend-experiment

services:
  # <<: *base
  http-server:
    container_name: http-server
    build:
      context: ./containers/http-server
    image: containters/http-server
    volumes:
      - ./volume/nginx/html/:/usr/share/nginx/html
    ports:
      - "${HTTP_SERVER_PORT}:80"

  http-server-proxy:
    container_name: http-server-proxy
    build:
      context: ./containers/blob-reverse-proxy
    image: containters/http-server-proxy
    volumes:
      - ./volume/http-server-proxy/conf/:/etc/nginx/
    ports:
      - "18099:80"