version: '3.0'

# x-base: &base
#   networks: 
#     - microfrontend-experiment

services:
  # <<: *base
  http-server:
    container_name: http-server
    build:
      context: ./containers/http-server
    image: containters/http-server
    volumes:
      - ./volume/nginx/html/:/usr/share/nginx/html
      - ./volume/nginx/config/:/etc/nginx/
    ports:
      - "${HTTP_SERVER_PORT}:80"